name: fire
channels:
  - defaults
  - conda-forge
dependencies:
  - altair=3.3.0=py38_0
  - asn1crypto=1.2.0=py38_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py38_0
  - blas=1.0=mkl
  - bleach=3.1.0=py_0
  - ca-certificates=2019.11.27=0
  - certifi=2019.11.28=py38_0
  - cffi=1.13.2=py38h7a1dbc1_0
  - colorama=0.4.1=py_0
  - cryptography=2.8=py38h7a1dbc1_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py38_0
  - fire=0.2.1=py_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=64.2=he025d50_1
  - idna=2.8=py38_1000
  - importlib_metadata=1.1.0=py38_0
  - intel-openmp=2019.4=245
  - ipykernel=5.1.3=py38h39e3cac_0
  - ipython=7.10.1=py38h39e3cac_0
  - ipython_genutils=0.2.0=py38_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.15.1=py38_0
  - jinja2=2.10.3=py_0
  - jpeg=9c=hfa6e2cd_1001
  - json5=0.8.5=py_0
  - jsonschema=3.2.0=py38_0
  - jupyter=1.0.0=py_2
  - jupyter_client=5.3.4=py38_0
  - jupyter_console=6.0.0=py38_0
  - jupyter_core=4.6.1=py38_0
  - jupyterlab=1.2.3=py_0
  - jupyterlab_server=1.0.6=py_0
  - libclang=9.0.0=default_hf44288c_4
  - libpng=1.6.37=h2a8f88b_0
  - libsodium=1.0.16=h9d3ae62_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py38he774522_0
  - mistune=0.8.4=py38he774522_1000
  - mkl=2019.4=245
  - mkl-service=2.3.0=py38hb782905_0
  - mkl_fft=1.0.15=py38h14836fe_0
  - mkl_random=1.1.0=py38hf9181ef_0
  - more-itertools=7.2.0=py38_0
  - msys2-conda-epoch=20160418=1
  - nbconvert=5.6.1=py38_0
  - nbformat=4.4.0=py38_0
  - notebook=6.0.1=py38_0
  - numpy=1.17.4=py38h4320e6b_0
  - numpy-base=1.17.4=py38hc3f5095_0
  - openssl=1.1.1d=he774522_3
  - pandas=0.25.3=py38ha925a31_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py38_1
  - parso=0.5.1=py_0
  - pickleshare=0.7.5=py38_1000
  - pip=19.3.1=py38_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.10=py_0
  - pycparser=2.19=py_0
  - pygments=2.5.2=py_0
  - pyopenssl=19.1.0=py38_0
  - pyqt=5.12.3=py38h6538335_1
  - pyrsistent=0.15.6=py38he774522_0
  - pysocks=1.7.1=py38_0
  - python=3.8.0=hc9e8b01_5
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pywin32=225=py38hfa6e2cd_0
  - pywinpty=0.5.5=py38_1000
  - pyzmq=18.1.0=py38ha925a31_0
  - qt=5.12.5=h7ef1ec2_0
  - qtconsole=4.6.0=py_0
  - selenium=3.141.0=py38he774522_1000
  - send2trash=1.5.0=py38_0
  - setuptools=42.0.2=py38_0
  - six=1.13.0=py38_0
  - sqlite=3.30.1=hfa6e2cd_0
  - termcolor=1.1.0=py_2
  - terminado=0.8.3=py38_0
  - testpath=0.4.4=py_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py38he774522_0
  - traitlets=4.3.3=py38_0
  - urllib3=1.25.7=py38_0
  - vc=14.1=h0510ff6_4
  - vega=2.6.0=py38_0
  - vega_datasets=0.7.0=py_0
  - vs2015_runtime=14.16.27012=hf0eaf9b_0
  - wcwidth=0.1.7=py38_0
  - webencodings=0.5.1=py38_1
  - wheel=0.33.6=py38_0
  - widgetsnbextension=3.5.1=py38_0
  - win_inet_pton=1.1.0=py38_0
  - wincertstore=0.2=py38_1003
  - winpty=0.4.3=4
  - zeromq=4.3.1=h33f27b4_3
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h62dcd97_3
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
prefix: C:\Users\tiara\Anaconda3\envs\fire

